### ISSUE TITLE
Create mass-run-example - Running recipes in docker image on all orgs

### ISSUE THREAD

**Issue by pstreef** [moderneinc/mass-run-example#1]
Enable running a recipe on a set of orgs and collect results. Produce a reference implementation in a docker image with metrics, logs, and results in a spreadsheet similar to how mass-ingest template is done. ​​https://github.com/moderneinc/mass-ingest-example 
```
mod config moderne
mod config recipes moderne sync (how do we report partial errors from this? Just report not found recipes on individual repos?) 
mod config moderne organizations show
for each orgname
mod git clone moderne . orgname –metadata-only
mod build
mod run recipe
mod log runs add –org orgname plan.zip
curl -XPOST https://artifactory/runs-repo/io/moderne/plan/20240430/plan.zip < plan.zip
```

https://docs.google.com/document/d/18mtebL5P2U8RCa8JYRbmkJQrZQGwFjhH8G-6VEg1XMQ/edit

**Comment by pstreef** [comment]
Repository is set up.

**Comment by pstreef** [comment]
mass-run is now running against app.
It's producing files in artifactory under `https://artifactory.moderne.ninja/artifactory/run-logs/io/moderne/`


![Image](https://github.com/moderneinc/mass-run-example/assets/7645564/ce7dba04-3b79-4e18-867a-abccb12d681c)



[runs.xlsx](https://github.com/moderneinc/mass-run-example/files/15414565/runs.xlsx)

**Comment by pstreef** [comment]
Next step is to figure out how to partition organizations to make sure we can actually run on them. Right now when we hit `ALL` it takes forever because it tries to download and run on 50k repos.

We can not just cut up a csv like we do with mass-ingest, since the input here is coming from the output of other commands.

Perhaps we can build pagination into the clone (it currently supports limit, but not offset) and multi-repository commands (also limit offset).

cc @okundzich @kmccarp

**Comment by okundzich** [comment]
I believe metrics were removed from this?  I would rather we added them in.

Can we configure this to run on each child (no descendants) organization for now? Or a list of organizations rather than all the organizations defined in the org service?  We don't want to run this on ALL. 

I believe pagination still may be useful for large orgs like Apache, but it may still be fine, as it's 1000 repos, and we know amex did a run on 6k repos in their org locally on their workstation. It's easier to aggregate data if we don't partition orgs.

**Comment by pstreef** [comment]
Not sure what you mean, metrics are there? We removed prometheus/grafana from our own mass-run because we already run that separately (most people probably will) but it is still there in the example.

I think it would be easiest to either blacklist or whitelist orgs and run on those.

**Comment by okundzich** [comment]
i see, we removed metrics from our own mass-run.

How would you black list or white list organizations? We only run devcenter now on about 10 orgs and would want to enable something similar in mass run.

**Comment by pstreef** [comment]
Whitelisting is easiest, just put the exact orgs as a list in the script. We could do the same with blacklisting but then an external change can "break things" more easily.
Then when we extend to retrieving DevCenter we only run on orgs that actually have a DevCenter configured.

**Comment by pstreef** [comment]
We're now using a simple whitelist, this is also available in the example/script (can be switched to by commenting/uncommenting specific method calls in the script) 

I've added an alert if there are no successful runs in the last 30 minutes or the % of success falls under 50%. We'll have to see how this behaves and tweak it, but it's a start and would have alerted us about yesterdays issues.
